### ISSUE TITLE
Code completion incorrectly includes return type of the completion

### ISSUE THREAD

**Issue by deboer-tim** [atom/ide-java#20] opened 2017-09-13 20:20 UTC
The code completion popup window shows you the return type of type or method completions (which is handy) but then also pastes this syntax into your code when you use the completion, which causes compile failures.

For example, completing something like:
> String s = "test"; s.
will include the length() completion and show you it'll return an int. But it'll also paste that into your code:
> String s = "test"; s.length() : int
which gives a compile error.

**Comment by damieng** [comment] 2017-09-13 20:26
Duplicate of #10

**Closed by damieng** 2017-09-13 20:26 UTC
