### ISSUE TITLE
IDE-java bug

### ISSUE THREAD

**Issue by d8s3c** [atom/ide-java#75] opened 2018-04-30 09:29 UTC
I found a bug in the auto-completion of the text, sometimes when i type Sys , and it shows system and blabla... then i pressed ENTER and the auto-completion didn't work, so i have to type in again and then enter ,the second time i pressed enter the auto-completion works. So please fix this, i'm too afraid to fix the code myself 😄

Conclusion : I have to type twice to trigger the auto-completion.

Anything else is just working fine. Thanks for making my work easier

**Comment by rsese** [comment] 2018-04-30 23:28
What versions of Atom and ide-java are you running and what operating system?

Also, do you have the same problem with auto-complete in general (so not specific to using ide-java)?

**Comment by nrfaikar** [comment] 2018-05-05 10:09
In my opinion, this problem caused by conflict with language-java package....

**Comment by rsese** [comment] 2018-05-15 22:34
Thanks @nrfaikar, do you have a specific example that I can try that shows the conflict?

**Comment by nrfaikar** [comment] 2018-05-20 13:16
I suggest to try JavaFX import snippets....

**Comment by KJ1010G** [comment] 2018-06-10 10:13
I am having this problem too. I have even added screen-shots in #84 to help explain better. For me it happens with all libraries.

**Comment by nrfaikar** [comment] 2018-06-10 11:42
Me too... Happens with all libraries...
Please fix it...

**Comment by KJ1010G** [comment] 2018-06-10 14:47
this bug was reported so long ago and still not fixed ?? is anyone even looking at it ?

**Comment by rsese** [comment] 2018-06-12 17:30
It would be super helpful if anyone could provide a small public test project where this reproduces along with repro steps to see the problem.

> I suggest to try JavaFX import snippets....

@nrfaikar sorry can you be more specific?  Specific repro steps in particular would be helpful.

**Comment by KJ1010G** [comment] 2018-06-13 05:48
@rsese 

Steps
-------
1. Fresh install latest version of atom (on Ubuntu 16.04)
2. Create any java project. The auto-completion provided by default should work fine.(For example when you type main and press tab).
3. Install the latest version of atom-ide-ui.
4. Install the latest version of ide-java.
5. Create any java project which imports a library(It can be any Library). (I will add a file, you can use it).
6. Type all the code from start and use auto-completion as much as possible.
7. Notice how many times auto-complete does not work on first time. The way I suggested in #84 .

NOTE - Just rename this file to SimpleAnimation.java and then open it on atom.
[SimpleAnimation.txt](https://github.com/atom/ide-java/files/2096743/SimpleAnimation.txt)

**Comment by rsese** [comment] 2018-06-13 21:39
Thanks a lot @KJ1010G :bow:  I'm able to reproduce with just this bit of code:

```java
import javax.swing.*;

public class Test {
	public static void main(String[] args) {
		JFrame frame = new JFrame();
		frame.
	}
}
```

And trying to autocomplete from `frame.`.  Going to go ahead and close this in favor of #84 since the issue body is more detailed and I'll add the repro steps [above](https://github.com/atom/ide-java/issues/75#issuecomment-396820888) there as well (slightly edited to add more detail for step-by-step reproduction).

**Closed by rsese** 2018-06-13 21:39 UTC
