### ISSUE TITLE
Uncaught Error: Header must provide a Content-Length property.

### ISSUE THREAD

**Issue by ungb** [atom/ide-java#11] opened 2017-09-12 17:13 UTC
[Enter steps to reproduce:]

1. Open a Java file
2. Close the java file.

![close](https://user-images.githubusercontent.com/5624870/30339233-36a24630-97a3-11e7-9d6e-386bca62dcf4.gif)

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [ide-java](https://github.com/atom/ide-java) package 0.6.0

### Stack Trace

Uncaught Error: Header must provide a Content-Length property.

```
At /Users/bungdonuts/github/packages/ide-java/node_modules/vscode-jsonrpc/lib/messageReader.js:191

Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (/packages/ide-java/node_modules/vscode-jsonrpc/lib/messageReader.js:191:27)
    at /packages/ide-java/node_modules/vscode-jsonrpc/lib/messageReader.js:176:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

### Commands

```
     -0:20.5.0 application:reopen-project (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.15 
atom-ide-ui 0.3.0 
chester-atom-syntax 0.3.0 
chestnut-light-atom-syntax 0.2.1 
docks-test 0.0.0 
ide-java 0.6.0 
language-typescript-grammars-only 1.6.0 
preview-inline 1.4.7 
pure-syntax 0.3.0 
real-time 0.1.0 
```

**Comment by damieng** [comment] 2017-09-12 17:20
Duplicate of #8

**Closed by damieng** 2017-09-12 17:20 UTC
