### ISSUE TITLE
Inappropriate variable and method suggestions

### ISSUE THREAD

**Issue by thevella** [atom/ide-java#57] opened 2018-02-13 04:44 UTC
**Atom:** 1.23.3 x64
**ide-java:** 0.7.0

ide-java suggests variables and methods previously used after every semi-colon. Additionally (I do not know if this is a limitation of the engine or of ide-java) variables and methods are suggested when typing comments.

**Comment by damieng** [comment] 2018-02-13 05:14
This is actually controlled by the upstream language server at https://github.com/eclipse/eclipse.jdt.ls

I would imagine they could do something to prevent this in comments although suggesting variable names after a semicolon would seem to be the correct behavior.

**Comment by fbricon** [comment] 2018-02-27 20:51
The problem is caused by atom requesting content assist on all keystrokes apparently.

I can see VSCode behaves differently. I'd get the same behavior though when hitting cmd+space (forcing autocompletion) after a `;`

**Comment by damieng** [comment] 2018-02-27 20:56
Sorry, this turned out to be an issue in our bridging library (atom-languageclient) - we have a fix for it going out today.

**Comment by damieng** [comment] 2018-02-27 23:32
This should now be fixed in today's 0.8.0 release!

**Closed by damieng** 2018-02-27 23:32 UTC
