### ISSUE TITLE
Uncaught Error: Message header must separate key and value using :

### ISSUE THREAD

**Issue by StomX** [atom/ide-java#22] opened 2017-09-14 01:32 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [ide-java](https://github.com/atom/ide-java) package 0.6.0

### Stack Trace

Uncaught Error: Message header must separate key and value using :

```
At C:\Users\Jay\.atom\packages\ide-java\node_modules\vscode-jsonrpc\lib\messageReader.js:68

Error: Message header must separate key and value using :
    at /packages/ide-java/node_modules/vscode-jsonrpc/lib/messageReader.js:68:23
    at Array.forEach (native)
    at MessageBuffer.tryReadHeaders (/packages/ide-java/node_modules/vscode-jsonrpc/lib/messageReader.js:65:17)
    at StreamMessageReader.onData (/packages/ide-java/node_modules/vscode-jsonrpc/lib/messageReader.js:185:43)
    at /packages/ide-java/node_modules/vscode-jsonrpc/lib/messageReader.js:176:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

### Commands

```
     -2:51.7.0 editor:consolidate-selections (input.hidden-input)
     -2:51.7.0 core:cancel (input.hidden-input)
     -2:30.9.0 command-palette:toggle (div.tool-panel.tree-view)
  2x -2:28.3.0 core:move-down (input.hidden-input)
     -2:27.5.0 core:move-up (input.hidden-input)
     -2:27.2.0 core:confirm (input.hidden-input)
     -2:27.2.0 atom-maven:clean (div.tool-panel.tree-view)
     -1:36 command-palette:toggle (div.tool-panel.tree-view)
     -1:28.8.0 editor:consolidate-selections (input.hidden-input)
     -1:28.8.0 core:cancel (input.hidden-input)
     -1:13.9.0 command-palette:toggle (div.tool-panel.tree-view)
  2x -1:11.9.0 core:move-down (input.hidden-input)
     -1:11 core:confirm (input.hidden-input)
     -1:11 settings-view:install-packages-and-themes (div.tool-panel.tree-view)
 13x -0:22.6.0 core:backspace (input.hidden-input)
     -0:20.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.3.1 
atom-maven 1.3.0 
emmet 2.4.3 
git-plus 7.9.3 
highlight-selected 0.13.1 
ide-java 0.6.0 
language-htl 0.3.4 
todo-show 2.0.0 
```

**Comment by damieng** [comment] 2017-09-14 01:35
Duplicate of #16

**Closed by damieng** 2017-09-14 01:35 UTC
